
import type { User, Product, Rule, Alert, Transaction, LiveActivity } from '@/types';

// Raw product data provided by the user
const rawProducts = [
  // Electronics
  {
    id: 'elec-1',
    name: 'iPhone 15 Pro Max',
    price: 1199.99,
    imageUrl: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Electronics',
    description: 'Latest iPhone with titanium design and advanced camera system',
    inStock: true,
    rating: 4.8,
    reviews: 2847,
  },
  {
    id: 'elec-2',
    name: 'MacBook Pro 16"',
    price: 2499.99,
    imageUrl: 'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Electronics',
    description: 'Powerful laptop with M3 Pro chip for professional workflows',
    inStock: true,
    rating: 4.9,
    reviews: 1523,
  },
  {
    id: 'elec-3',
    name: 'Sony WH-1000XM5',
    price: 399.99,
    imageUrl: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Electronics',
    description: 'Industry-leading noise canceling wireless headphones',
    inStock: true,
    rating: 4.7,
    reviews: 3421,
  },
  {
    id: 'elec-4',
    name: 'Samsung 65" QLED TV',
    price: 1299.99,
    imageUrl: 'https://images.pexels.com/photos/1201996/pexels-photo-1201996.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Electronics',
    description: '4K QLED Smart TV with quantum dot technology',
    inStock: true,
    rating: 4.6,
    reviews: 892,
  },
  {
    id: 'elec-5',
    name: 'iPad Air 5th Gen',
    price: 599.99,
    imageUrl: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Electronics',
    description: 'Powerful tablet with M1 chip and stunning Liquid Retina display',
    inStock: true,
    rating: 4.8,
    reviews: 1876,
  },
  {
    id: 'elec-6',
    name: 'Nintendo Switch OLED',
    price: 349.99,
    imageUrl: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Electronics',
    description: 'Gaming console with vibrant OLED screen',
    inStock: true,
    rating: 4.7,
    reviews: 2134,
  },
  {
    id: 'elec-7',
    name: 'Canon EOS R6 Mark II',
    price: 2499.99,
    imageUrl: 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Electronics',
    description: 'Professional mirrorless camera with 24.2MP sensor',
    inStock: false,
    rating: 4.9,
    reviews: 567,
  },
  {
    id: 'elec-8',
    name: 'Apple Watch Series 9',
    price: 429.99,
    imageUrl: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Electronics',
    description: 'Advanced smartwatch with health monitoring features',
    inStock: true,
    rating: 4.8,
    reviews: 3245,
  },
  {
    id: 'elec-9',
    name: 'Dyson V15 Detect',
    price: 749.99,
    imageUrl: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Electronics',
    description: 'Cordless vacuum with laser dust detection',
    inStock: true,
    rating: 4.6,
    reviews: 1432,
  },
  {
    id: 'elec-10',
    name: 'Tesla Model Y Charger',
    price: 599.99,
    imageUrl: 'https://images.pexels.com/photos/7078619/pexels-photo-7078619.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Electronics',
    description: 'High-speed home charging solution for Tesla vehicles',
    inStock: true,
    rating: 4.7,
    reviews: 823,
  },
  {
    id: 'men-1',
    name: 'Premium Cotton T-Shirt',
    price: 29.99,
    imageUrl: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Men',
    description: 'Soft, breathable cotton t-shirt in classic fit',
    inStock: true,
    rating: 4.5,
    reviews: 1234,
  },
  {
    id: 'men-2',
    name: 'Slim Fit Denim Jeans',
    price: 89.99,
    imageUrl: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Men',
    description: 'Modern slim fit jeans with stretch comfort',
    inStock: true,
    rating: 4.6,
    reviews: 2156,
  },
  {
    id: 'men-3',
    name: 'Wool Blend Suit Jacket',
    price: 299.99,
    imageUrl: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Men',
    description: 'Tailored wool blend blazer for professional occasions',
    inStock: true,
    rating: 4.8,
    reviews: 567,
  },
  {
    id: 'men-4',
    name: 'Casual Button-Down Shirt',
    price: 59.99,
    imageUrl: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Men',
    description: 'Versatile cotton shirt perfect for casual or business casual',
    inStock: true,
    rating: 4.4,
    reviews: 1876,
  },
  {
    id: 'men-5',
    name: 'Athletic Performance Shorts',
    price: 39.99,
    imageUrl: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Men',
    description: 'Moisture-wicking shorts for workouts and sports',
    inStock: true,
    rating: 4.7,
    reviews: 2341,
  },
  {
    id: 'men-6',
    name: 'Leather Dress Shoes',
    price: 179.99,
    imageUrl: 'https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Men',
    description: 'Genuine leather oxford shoes for formal occasions',
    inStock: true,
    rating: 4.6,
    reviews: 892,
  },
  {
    id: 'men-7',
    name: 'Hooded Sweatshirt',
    price: 69.99,
    imageUrl: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Men',
    description: 'Comfortable fleece hoodie for casual wear',
    inStock: true,
    rating: 4.5,
    reviews: 1654,
  },
  {
    id: 'men-8',
    name: 'Winter Puffer Jacket',
    price: 149.99,
    imageUrl: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Men',
    description: 'Insulated jacket for cold weather protection',
    inStock: false,
    rating: 4.8,
    reviews: 743,
  },
  {
    id: 'men-9',
    name: 'Running Sneakers',
    price: 129.99,
    imageUrl: 'https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Men',
    description: 'Lightweight running shoes with advanced cushioning',
    inStock: true,
    rating: 4.7,
    reviews: 2987,
  },
  {
    id: 'men-10',
    name: 'Polo Shirt',
    price: 49.99,
    imageUrl: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Men',
    description: 'Classic polo shirt in premium pique cotton',
    inStock: true,
    rating: 4.4,
    reviews: 1432,
  },
  {
    id: 'women-1',
    name: 'Floral Summer Dress',
    price: 79.99,
    imageUrl: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Women',
    description: 'Elegant floral print dress perfect for summer occasions',
    inStock: true,
    rating: 4.6,
    reviews: 1876,
  },
  {
    id: 'women-2',
    name: 'High-Waisted Skinny Jeans',
    price: 94.99,
    imageUrl: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Women',
    description: 'Flattering high-waisted jeans with stretch fabric',
    inStock: true,
    rating: 4.7,
    reviews: 2543,
  },
  {
    id: 'women-3',
    name: 'Silk Blouse',
    price: 119.99,
    imageUrl: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Women',
    description: 'Luxurious silk blouse for professional and evening wear',
    inStock: true,
    rating: 4.8,
    reviews: 987,
  },
  {
    id: 'women-4',
    name: 'Yoga Leggings',
    price: 54.99,
    imageUrl: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Women',
    description: 'High-performance leggings for yoga and fitness',
    inStock: true,
    rating: 4.9,
    reviews: 3421,
  },
  {
    id: 'women-5',
    name: 'Cashmere Sweater',
    price: 189.99,
    imageUrl: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Women',
    description: 'Soft cashmere sweater for luxury comfort',
    inStock: true,
    rating: 4.8,
    reviews: 1234,
  },
  {
    id: 'women-6',
    name: 'Designer Handbag',
    price: 249.99,
    imageUrl: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Women',
    description: 'Elegant leather handbag with gold hardware',
    inStock: true,
    rating: 4.7,
    reviews: 1654,
  },
  {
    id: 'women-7',
    name: 'High Heel Pumps',
    price: 139.99,
    imageUrl: 'https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Women',
    description: 'Classic pointed-toe pumps for formal occasions',
    inStock: true,
    rating: 4.5,
    reviews: 876,
  },
  {
    id: 'women-8',
    name: 'Maxi Skirt',
    price: 69.99,
    imageUrl: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Women',
    description: 'Flowing maxi skirt in breathable fabric',
    inStock: false,
    rating: 4.6,
    reviews: 1432,
  },
  {
    id: 'women-9',
    name: 'Sports Bra',
    price: 34.99,
    imageUrl: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Women',
    description: 'Supportive sports bra for high-intensity workouts',
    inStock: true,
    rating: 4.7,
    reviews: 2876,
  },
  {
    id: 'women-10',
    name: 'Trench Coat',
    price: 199.99,
    imageUrl: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Women',
    description: 'Classic trench coat for timeless style',
    inStock: true,
    rating: 4.8,
    reviews: 1098,
  },
  {
    id: 'grocery-1',
    name: 'Organic Avocados (6 pack)',
    price: 8.99,
    imageUrl: 'https://images.pexels.com/photos/557659/pexels-photo-557659.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Groceries',
    description: 'Fresh organic avocados, perfect for healthy meals',
    inStock: true,
    rating: 4.5,
    reviews: 432,
  },
  {
    id: 'grocery-2',
    name: 'Wild Salmon Fillet',
    price: 24.99,
    imageUrl: 'https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Groceries',
    description: 'Premium wild-caught salmon, rich in omega-3',
    inStock: true,
    rating: 4.8,
    reviews: 876,
  },
  {
    id: 'grocery-3',
    name: 'Artisan Sourdough Bread',
    price: 6.99,
    imageUrl: 'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Groceries',
    description: 'Freshly baked sourdough with crispy crust',
    inStock: true,
    rating: 4.7,
    reviews: 654,
  },
  {
    id: 'grocery-4',
    name: 'Organic Baby Spinach',
    price: 4.99,
    imageUrl: 'https://images.pexels.com/photos/1656666/pexels-photo-1656666.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Groceries',
    description: 'Fresh organic baby spinach leaves',
    inStock: true,
    rating: 4.6,
    reviews: 321,
  },
  {
    id: 'grocery-5',
    name: 'Free-Range Eggs (12 count)',
    price: 7.99,
    imageUrl: 'https://images.pexels.com/photos/162712/egg-white-food-protein-162712.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Groceries',
    description: 'Farm-fresh free-range eggs from happy hens',
    inStock: true,
    rating: 4.8,
    reviews: 1234,
  },
  {
    id: 'grocery-6',
    name: 'Greek Yogurt (32oz)',
    price: 5.99,
    imageUrl: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Groceries',
    description: 'Creamy Greek yogurt packed with protein',
    inStock: true,
    rating: 4.5,
    reviews: 987,
  },
  {
    id: 'grocery-7',
    name: 'Organic Quinoa (2 lbs)',
    price: 12.99,
    imageUrl: 'https://images.pexels.com/photos/793785/pexels-photo-793785.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Groceries',
    description: 'Nutritious organic quinoa, complete protein source',
    inStock: true,
    rating: 4.7,
    reviews: 543,
  },
  {
    id: 'grocery-8',
    name: 'Grass-Fed Ground Beef (1 lb)',
    price: 16.99,
    imageUrl: 'https://images.pexels.com/photos/3688/food-dinner-lunch-unhealthy.jpg?auto=compress&cs=tinysrgb&w=500',
    category: 'Groceries',
    description: 'Premium grass-fed ground beef, 85% lean',
    inStock: false,
    rating: 4.9,
    reviews: 765,
  },
  {
    id: 'grocery-9',
    name: 'Organic Blueberries (1 pint)',
    price: 6.99,
    imageUrl: 'https://images.pexels.com/photos/357573/pexels-photo-357573.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Groceries',
    description: 'Sweet organic blueberries, antioxidant-rich',
    inStock: true,
    rating: 4.6,
    reviews: 432,
  },
  {
    id: 'grocery-10',
    name: 'Almond Milk (64oz)',
    price: 4.49,
    imageUrl: 'https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Groceries',
    description: 'Unsweetened almond milk, dairy-free alternative',
    inStock: true,
    rating: 4.4,
    reviews: 876,
  }
];

// Add `isInWishlist` to a few items for demonstration
export const mockProducts: Product[] = rawProducts.map((product, index) => ({
  ...product,
  isInWishlist: [1, 4, 6, 12, 25].includes(index), // Add a few items to the wishlist
}));


const sampleUserIps = ['192.168.1.101', '10.0.0.55', '172.16.3.20', '203.0.113.45', '198.51.100.12'];
const sampleLocations = ['USA', 'Canada', 'Germany', 'UK', 'France'];
const sampleDeviceFingerprints = [
  'Chrome/Win10/1920x1080/UTC-5',
  'Safari/MacOS/2560x1440/UTC+1',
  'Firefox/Linux/1366x768/UTC+0',
  'Edge/Win11/1920x1080/UTC-8',
  'Chrome/Android/1080x2340/UTC+5:30',
];

export const mockUsers: User[] = Array.from({ length: 10 }, (_, i) => ({
  id: `user-${i + 1}`,
  email: `user${i + 1}@example.com`,
  name: `User ${i + 1}`,
  ipAddress: sampleUserIps[i % sampleUserIps.length],
  ipLocation: sampleLocations[i % sampleLocations.length],
  deviceFingerprint: sampleDeviceFingerprints[i % sampleDeviceFingerprints.length],
  avgTypingSpeedLogin: parseFloat((Math.random() * 7 + 1).toFixed(2)), // 1 to 8 kps
  passwordPasted: Math.random() > 0.8,
  trustScore: Math.floor(Math.random() * 70 + 30), // 30 to 100
  status: i % 3 === 0 ? 'Suspicious' : i % 3 === 1 ? 'Monitor' : 'Safe',
  lastActivity: new Date(Date.now() - Math.random() * 1000000000).toISOString(),
  deviceReuseCount: Math.floor(Math.random() * 5),
  billingCountry: sampleLocations[(i+1) % sampleLocations.length], // Sometimes different
  transactions: [],
  alerts: []
}));

mockUsers.forEach(user => {
  if (user.status === 'Suspicious') {
    user.trustScore = Math.floor(Math.random() * 20 + 30); // 30-49
  } else if (user.status === 'Monitor') {
    user.trustScore = Math.floor(Math.random() * 30 + 50); // 50-79
  } else {
    user.trustScore = Math.floor(Math.random() * 20 + 80); // 80-100
  }
});


export const mockRules: Rule[] = [
  { id: 'rule-1', name: 'Abnormal Typing Speed (Login)', condition: 'typing_speed_login < 1 || typing_speed_login > 8', action: 'risk += 10', description: 'Detects unusually slow or fast typing during login.', isEnabled: true, category: 'Typing', severityImpact: 10 },
  { id: 'rule-2', name: 'High Device Reuse', condition: 'device_reuse_count > 3', action: 'risk += 15', description: 'Flags devices used across multiple accounts.', isEnabled: true, category: 'Device', severityImpact: 15 },
  { id: 'rule-3', name: 'IP vs. Billing Country Mismatch', condition: 'ip_location !== billing_country', action: 'risk += 20', description: 'Detects discrepancies between IP geolocation and billing country.', isEnabled: true, category: 'Location', severityImpact: 20 },
  { id: 'rule-4', name: 'Password Paste (Login)', condition: 'password_pasted_login === true', action: 'risk += 5', description: 'Indicates if password was pasted, common for bots.', isEnabled: true, category: 'Typing', severityImpact: 5 },
  { id: 'rule-5', name: 'Short Checkout Duration', condition: 'checkout_duration < 5', action: 'risk += 10', description: 'Flags unusually fast checkout process (in seconds).', isEnabled: false, category: 'Transaction', severityImpact: 10 },
  { id: 'rule-6', name: 'Proxy/VPN Detected', condition: 'proxy_vpn_detected === true', action: 'risk += 25', description: 'Detects usage of proxies or VPNs.', isEnabled: true, category: 'Location', severityImpact: 25 },
];

export const mockAlerts: Alert[] = mockUsers
  .filter(u => u.status === 'Suspicious' || u.status === 'Monitor')
  .slice(0, 5) // Take first 5 suspicious/monitored users
  .map((user, i) => ({
    id: `alert-${i + 1}`,
    userId: user.id,
    userName: user.name,
    userEmail: user.email,
    timestamp: new Date(Date.now() - Math.random() * 100000000).toISOString(),
    message: `User ${user.name} triggered ${user.status === 'Suspicious' ? 'high' : 'medium'} risk alert.`,
    severity: user.status === 'Suspicious' ? 'High' : 'Medium',
    reason: user.status === 'Suspicious' ? 'Multiple risk factors: IP/Billing mismatch, high device reuse.' : 'Unusual typing speed.',
    isRead: Math.random() > 0.5,
  }));

export const mockTransactions: Transaction[] = mockUsers.map((user, i) => ({
  id: `txn-${i+1}`,
  userId: user.id,
  userEmail: user.email,
  items: [
    { ...mockProducts[i % mockProducts.length], quantity: 1 },
    ...(i % 2 === 0 ? [{ ...mockProducts[(i + 1) % mockProducts.length], quantity: Math.floor(Math.random()*2+1) }] : [])
  ],
  totalAmount: parseFloat((Math.random() * 500 + 50).toFixed(2)),
  timestamp: new Date(Date.now() - Math.random() * 2000000000).toISOString(),
  checkoutDuration: Math.floor(Math.random() * 120 + 3), // 3 to 123 seconds
  ipCountry: user.ipLocation,
  billingCountry: user.billingCountry,
  typingSpeedPayment: parseFloat((Math.random() * 7 + 1).toFixed(2)),
  typingSpeedShipping: parseFloat((Math.random() * 7 + 1).toFixed(2)),
  status: user.trustScore < 50 ? 'Pending Review' : 'Completed'
}));

mockUsers.forEach(user => {
  user.transactions = mockTransactions.filter(t => t.userId === user.id);
  user.alerts = mockAlerts.filter(a => a.userId === user.id);
});


export const mockLiveActivities: LiveActivity[] = [
  { id: 'la-1', timestamp: new Date().toISOString(), userId: 'user-1', userEmail: 'user1@example.com', action: 'Login Attempt', riskScore: 45, details: { ip: '192.168.1.101' }, isSuspicious: true },
  { id: 'la-2', timestamp: new Date(Date.now() - 5000).toISOString(), userId: 'user-2', userEmail: 'user2@example.com', action: 'Viewed Product "Quantum Laptop X1"', riskScore: 85, isSuspicious: false },
  { id: 'la-3', timestamp: new Date(Date.now() - 10000).toISOString(), userId: 'user-1', userEmail: 'user1@example.com', action: 'Added to Cart "Nebula Smartwatch Z"', riskScore: 48, details: { quantity: 1 }, isSuspicious: true },
  { id: 'la-4', timestamp: new Date(Date.now() - 15000).toISOString(), userId: 'user-3', userEmail: 'user3@example.com', action: 'Checkout Started', riskScore: 70, isSuspicious: false },
  { id: 'la-5', timestamp: new Date(Date.now() - 20000).toISOString(), userId: 'user-4', userEmail: 'user4@example.com', action: 'Password Changed', riskScore: 65, isSuspicious: false },
  { id: 'la-6', timestamp: new Date(Date.now() - 25000).toISOString(), userId: 'user-1', userEmail: 'user1@example.com', action: 'Checkout Failed - Payment Declined', riskScore: 30, details: { reason: "Insufficient Funds" }, isSuspicious: true },
];

const MOCK_TOTAL_TRANSACTIONS = 542;
const MOCK_BLOCKED_TRANSACTIONS = 23;
export const mockFullAnalyticsData = {
  totalUsers: mockUsers.length,
  totalAnomalies: mockAlerts.filter(a => a.severity === "High" || a.severity === "Medium").length,
  avgTrustScore: parseFloat((mockUsers.reduce((sum, u) => sum + u.trustScore, 0) / mockUsers.length).toFixed(1)),
  dailyLoginTrends: [
    { date: 'Mon', logins: 65 },
    { date: 'Tue', logins: 72 },
    { date: 'Wed', logins: 80 },
    { date: 'Thu', logins: 85 },
    { date: 'Fri', logins: 92 },
    { date: 'Sat', logins: 105 },
    { date: 'Sun', logins: 98 },
  ],
  totalTransactions: MOCK_TOTAL_TRANSACTIONS,
  blockedTransactions: MOCK_BLOCKED_TRANSACTIONS,
  fraudDetectionRate: `${((MOCK_BLOCKED_TRANSACTIONS / MOCK_TOTAL_TRANSACTIONS) * 100).toFixed(2)}%`,
};

export const mockDashboardData = {
    analytics: {
        totalUsers: mockUsers.length,
        suspiciousActivitiesToday: mockAlerts.filter(a => new Date(a.timestamp).toDateString() === new Date().toDateString()).length,
        averageTrustScore: parseFloat((mockUsers.reduce((sum, u) => sum + u.trustScore, 0) / mockUsers.length).toFixed(1)),
        activeAlerts: mockAlerts.filter(a => !a.isRead).length
    },
    anomalies: mockAlerts.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()),
    recentOrders: mockTransactions.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()),
};
